site_name: MoneyMax Appointments API
site_description: Documentation for the Next.js appointments API

theme:
  name: readthedocs
nav:
  - Home: index.md
  - API: api.md
  - Configuration: configuration.md
docs_dir: docs
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
  - admonition